[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "NODE_ENV=production npm start"
healthcheckPath = "/api/test-connection"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
PORT = "3000" 